services:
  nameserver:
    build:
      context: ./nameserver
      dockerfile: Dockerfile.server
    container_name: nameserver
    networks:
      y-network:
        ipv4_address: 192.168.0.3
    ports:
      - "8080:8080"
  node1:
    build:
      context: ./namenode
      dockerfile: Dockerfile.node
    container_name: node1
    networks:
      y-network:
        ipv4_address: 192.168.0.4
  node2:
    build:
      context: ./namenode
      dockerfile: Dockerfile.node
    container_name: node2
    networks:
      y-network:
        ipv4_address: 192.168.0.5
networks:
  y-network:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.0.0/24"